export type SupportViewMode = "table" | "cards" | "full";

export interface SupportPanelProps {
  t: (key: string, ...args: any[]) => string;
  supportListText: Record<string, string>;
  tickets: any[];
  currentUser: any;
  sortByFilterData: any[];
  canUpdateSupport: boolean;
  canDeleteSupport: boolean;
  isLoading: boolean;
  search: string;
  total: number;
  perPage: number;
  currentPage: number;
  orderBy: string;
  orderDirection: string;
  openTicketActionMenuId: string;
  activeAdminPopoverKey: string;
  showArchived: boolean;
  viewMode: SupportViewMode;
  isMobileViewport: boolean;
  viewOptions: any[];
  ticketStatusActions: any[];
  perPageList: any[];
  totalPages: number;
  visiblePages: number[];
  currentTicketIdForChat: string | null;
  currentChatTicket: any;
  filtered: any[];
  setPage: (page: number) => Promise<void>;
  goPrev: () => Promise<void>;
  goNext: () => Promise<void>;
  getTicketChannelLabel: (channel: unknown, replyEmail?: unknown) => string;
  getTicketChannelBadgeClass: (channel: unknown, replyEmail?: unknown) => string;
  getTicketSourceKey: (ticket: any) => string;
  getTicketSourceLabel: (ticket: any) => string;
  getTicketSourceBadgeClass: (ticket: any) => string;
  getTicketStatusLabel: (status: unknown) => string;
  getTicketStatusDotClass: (status: unknown) => string;
  getTicketStatusActionClass: (status: string) => string;
  isTicketStatusActive: (ticket: any, status: string) => boolean;
  getTicketClientAvatarUrl: (ticket: any) => string;
  getTicketClientInitials: (ticket: any) => string;
  getTicketClientName: (ticket: any) => string;
  getTicketClientEmail: (ticket: any) => string;
  getTicketClientId: (ticket: any) => string;
  getTicketPreview: (ticket: any) => string;
  getTicketCreatedLabel: (ticket: any) => string;
  getTicketAdminParticipants: (ticket: any) => any[];
  getAdminParticipantId: (admin: any) => string;
  getAdminParticipantKey: (ticket: any, admin: any) => string;
  getAdminParticipantName: (admin: any) => string;
  getAdminParticipantEmail: (admin: any) => string;
  getAdminParticipantInitials: (admin: any) => string;
  getAdminParticipantAvatarUrl: (admin: any) => string;
  isCurrentAdminTicketParticipant: (ticket: any) => boolean;
  handleViewModeChange: (mode: string) => void;
  handleToggleArchived: () => Promise<void>;
  handleInputSearch: (value: string) => Promise<void>;
  handleClickUpdate: () => Promise<void>;
  toggleTicketActionMenu: (ticketId: unknown) => void;
  setActiveAdminPopoverKey: (key: string) => void;
  clearActiveAdminPopoverKey: () => void;
  toggleAdminPopover: (ticket: any, admin: any) => void;
  isTicketActionLoading: (ticket: any) => boolean;
  handleChangeTicketStatus: (ticket: any, status: string) => Promise<void>;
  handleArchiveTicket: (ticket: any) => Promise<void>;
  openAdminProfile: (admin: any) => Promise<void>;
  handleChangeFilterSortBy: (value: string) => Promise<void>;
  handleOrderByAndDirection: (value: string) => Promise<void>;
  handleCloseChat: () => void;
  handleChangePerPage: (newPerPage: number) => Promise<void>;
  handleClickRow: (ticketId: string) => Promise<void>;
  openTicketClient: (ticket: any) => void;
  handleChatIconClick: (ticket: any) => void;
  handleFloatingChatJoined: () => Promise<void>;
}
